### ISSUE TITLE
Doesn't seem to work with Rails 3 beta4

### ISSUE THREAD

**Issue by kristianmandrup** [binarylogic/searchlogic#103]
/Users/kristianconsult/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.0.0.beta4/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`merge_joins' for class `Class' (NameError)
    from /Users/kristianconsult/.rvm/gems/ruby-1.9.2-head/gems/activesupport-3.0.0.beta4/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
    from /Users/kristianconsult/Development/Languages/Ruby/Apps/Web-apps/Rails/Rails-3/Experimental/netzke-rails3-playground/vendor/plugins/searchlogic/lib/searchlogic/active_record/consistency.rb:8:in `block in included'
    from /Users/kristianconsult/Development/Languages/Ruby/Apps/Web-apps/Rails/Rails-3/Experimental/netzke-rails3-playground/vendor/plugins/searchlogic/lib/searchlogic/active_record/consistency.rb:7:in`class_eval'
    from /Users/kristianconsult/Development/Languages/Ruby/Apps/Web-apps/Rails/Rails-3/Experimental/netzke-rails3-playground/vendor/plugins/searchlogic/lib/searchlogic/active_record/consistency.rb:7:in `included'
    from /Users/kristianconsult/Development/Languages/Ruby/Apps/Web-apps/Rails/Rails-3/Experimental/netzke-rails3-playground/vendor/plugins/searchlogic/lib/searchlogic.rb:25:in`include'

**Comment by sjain** [comment]
same happens with rails 2.3.8 and bundler (can't seem to reproduce without bundler on 2.3.8)

**Comment by kristianmandrup** [comment]
For Rails 3, I substituted searchlogic for meta_where. No problemo!
Dunno about Rails 2.3.x.
