### ISSUE TITLE
rails 3 support

### ISSUE THREAD

**Issue by mixtli** [binarylogic/searchlogic#65]
After upgrading to rails 3, I get the following when I start the server:

/Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`merge_joins' for class `Class' (NameError)
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0.beta/lib/active_support/core_ext/module/aliasing.rb:31:in`alias_method_chain'
    from /Library/Ruby/Gems/1.8/gems/searchlogic-2.4.10/lib/searchlogic/active_record/consistency.rb:8:in `included'
    from /Library/Ruby/Gems/1.8/gems/searchlogic-2.4.10/lib/searchlogic/active_record/consistency.rb:7:in`class_eval'
    from /Library/Ruby/Gems/1.8/gems/searchlogic-2.4.10/lib/searchlogic/active_record/consistency.rb:7:in `included'
    from /Library/Ruby/Gems/1.8/gems/searchlogic-2.4.10/lib/searchlogic.rb:18:in`include'
    from /Library/Ruby/Gems/1.8/gems/searchlogic-2.4.10/lib/searchlogic.rb:18

**Comment by wtn** [comment]
duplicate, see pacoguzman's ticket

**Comment by sjain** [comment]
same happens with rails 2.3.8 and bundler

**Comment by yorzi** [comment]
I still can use searchlogic in rails 3. is there anyone using searchlogic in rials successfully?

**Comment by bowsersenior** [comment]
The bad news: searchlogic has a lot of stuff that's based on the ActiveRecord 2, so it might be hard to upgrade it to work with ActiveRecord 3 (and Rails 3).

The good news: meta_search works with rails 3 and uses almost the same syntax as searchlogic : http://github.com/ernie/meta_search

I switched over a large app from searchlogic to metasearch just by renaming the searchlogic `order` method to `sort_link` (the metasearch equivalent)

**Comment by runlevel5** [comment]
spree project has ported searchlogic to rails3, called 'rd_searchlogic'

**Comment by metasoarous** [comment]
I think I'll use rd_searchlogic for now, but are there plans for making the gem Rails 3 compatible here? An eta?

**Comment by phlegx** [comment]
It is working now for rail 3.0.3 or not?

Bye

**Comment by singhkishan** [comment]
rd and searchlogic both are not compatible  for rails 3 better to go for manual query
